[workspace]
members = [
    "ledger-generic",
    "ledger-transport",
    "ledger-transport-hid",
    "bip44",
]

exclude = [
  "examples/wasm"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
